name: test-action

on: 
  workflow_dispatch:

jobs:
    test1:
        runs-on: ubuntu-latest
        environment: ${{ inputs.env }}
        steps:
            - run: echo "arr=1,2,3,4,5" >> $GITHUB_ENV
            - run: |
                for reg in "${arr[@]}"
                do
                  echo reg
                done
