name: test-action

on: 
  workflow_dispatch:

jobs:
    test1:
        runs-on: ubuntu-latest
        environment: ${{ inputs.env }}
        steps:
            - name: print-secret
              run: echo "::notice title=test1::This is output from job test1"

    test2:
        needs: test1
        runs-on: ubuntu-latest
        steps:
          - run: | 
              echo '::notice title=test2::This is the output from job test2'
              exit 1

    test3:
        if: failure()
        needs: test2
        runs-on: ubuntu-latest
        steps:
          - run: echo '::notice title=test3::The job test2 has failed'

    test4:
        needs: test1
        runs-on: ubuntu-latest
        steps:
          - run: echo '::notice title=test4::This is the output from job test4'
