name: test-action

on: 
  workflow_dispatch:

jobs:
    test1:
        runs-on: ubuntu-latest
        permissions: write-all        
        steps:
            - uses: action/checkout@v3
            - run: |
                git config --global user.name "TTC-CCF"
                git config --global user.email "93956496+TTC-CCF@users.noreply.github.com"
                echo "Hello World!" > hello.txt
                git add -A
                git commit -m "chore: test user"
                git push origin ${{ github.ref_name }}
                
                
