name: test-action

on: 
  workflow_dispatch:

jobs:
    test1:
        runs-on: ubuntu-latest
        environment: ${{ inputs.env }}
        steps:
            - run: |
                a='1,2,3,4,5'
                echo "a=($a)" >> $GITHUB_ENV
            - run: |
                while IFS=',' read -r ele
                do
                  echo $ele
                done <<< "$a"
