name: test-action

on: 
  workflow_dispatch:
    inputs:
      env: 
        type: choice
        options:
          - approve
          - 

jobs:
    test-array-secret:
        runs-on: ubuntu-latest
        environment: ${{ inputs.env }}
        steps:
            - name: print-secret
              run: echo "hello!"