name: test-action

on: 
  workflow_dispatch:

jobs:
    test1:
        runs-on: ubuntu-latest
        environment: ${{ inputs.env }}
        steps:
            - run: |
                a='1,2,3,4,5'
                IFS=',' read -r -a I <<< "$a"
                echo $a
                echo "a=$a" >> $GITHUB_ENV
            - run: |
                for reg in "${arr[@]}"
                do
                  echo $reg
                done
